Repository rubizza-camp/summer-2019, pull requests merged in 2019-07, with the labels that each got.

#422 204-2
  204/2/Gemfile
  204/2/Gemfile.lock
  204/2/README.txt
  204/2/bot.rb
  204/2/commands/bot_response.rb
  204/2/commands/check.rb
  204/2/commands/geolocation.rb
  204/2/commands/photo.rb
  204/2/commands/redis_helper.rb
  204/2/commands/register.rb
  204/2/commands/start.rb
  204/2/commands/status.rb
  204/2/users.yaml
Labels: SPB

#424 3135-2
  3135/2/.env.example
  3135/2/.gitignore
  3135/2/Gemfile
  3135/2/Gemfile.lock
  3135/2/lib/action_status.rb
  3135/2/lib/db.rb
  3135/2/lib/event_handler.rb
  3135/2/lib/reception.rb
  3135/2/lib/registration.rb
  3135/2/lib/request_status.rb
  3135/2/lib/status.rb
  3135/2/lib/user.rb
  3135/2/lib/utils.rb
  3135/2/np_bouncer_bot.rb
  3135/2/recruit_list.yml
  3135/2/registered_list.yml
Labels: SPB

#438 3600 - 2
  3600/2/Gemfile
  3600/2/Gemfile.lock
  3600/2/commands/check_number.rb
  3600/2/commands/checkin.rb
  3600/2/commands/checkout.rb
  3600/2/download.rb
  3600/2/env.sample
  3600/2/identifiers.rb
  3600/2/members.yml
  3600/2/top_bot.rb
Labels: requires respond

#465 3545 - 2
  3545/2/.gitignore
  3545/2/Gemfile
  3545/2/Gemfile.lock
  3545/2/commands/checkin.rb
  3545/2/commands/checkout.rb
  3545/2/commands/start.rb
  3545/2/data.csv
  3545/2/webhooks_controller.rb
Labels: requires respond

#434 3545-1
  3545/1/Gemfile
  3545/1/Gemfile.lock
  3545/1/alternative_file.yaml
  3545/1/info_collector.rb
  3545/1/link_builder.rb
  3545/1/points_calculator.rb
  3545/1/table_builder.rb
  3545/1/top_gems.rb
  3545/1/top_gems.yaml
  3545/1/yaml_parser.rb
Labels: requires respond

#452 3634-2
  3634/2/.gitignore
  3634/2/Gemfile
  3634/2/Gemfile.lock
  3634/2/commands/check_in.rb
  3634/2/commands/check_out.rb
  3634/2/commands/start.rb
  3634/2/data.yml
  3634/2/env.sample
  3634/2/helpers/event_handler.rb
  3634/2/helpers/image_loader.rb
  3634/2/helpers/save_files.rb
  3634/2/workflow_checker.rb
Labels: requires respond

#377 3520 - 1
  3520/1/.gitignore
  3520/1/Gemfile
  3520/1/Gemfile.lock
  3520/1/lib/backup.rb
  3520/1/lib/data_converter.rb
  3520/1/lib/gems_data.rb
  3520/1/lib/option_validation.rb
  3520/1/lib/output_table.rb
  3520/1/lib/repo_scrapper.rb
  3520/1/lib/rubygems_links.rb
  3520/1/lib/tg_parse.rb
  3520/1/top_gems.rb
  3520/1/yaml/gems.yml
  3520/1/yaml/gems2.yml
Labels: requires respond

#329 3587-1
  3587/1/Gemfile
  3587/1/Gemfile.lock
  3587/1/file.txt
  3587/1/lib/analize_stats.rb
  3587/1/lib/data/gem.yml
  3587/1/lib/error.rb
  3587/1/lib/fill_output.rb
  3587/1/lib/fill_row.rb
  3587/1/lib/gem_list.rb
  3587/1/lib/gem_page.rb
  3587/1/lib/options.rb
  3587/1/lib/scrape_info.rb
  3587/1/lib/top_gems.rb
  3587/1/main.rb
Labels: Missed Deadline

#485 3444 - 2
  3444/2/.env.sample
  3444/2/.gitignore
  3444/2/Gemfile
  3444/2/Gemfile.lock
  3444/2/app.rb
  3444/2/commands/check_in.rb
  3444/2/commands/check_out.rb
  3444/2/commands/start.rb
  3444/2/data/list.yml
  3444/2/helpers/geo_helper.rb
  3444/2/helpers/path_helper.rb
  3444/2/helpers/photo_helper.rb
Labels: requires respond

#501 3761 - 3
  3761/3/.env.sample
  3761/3/.gitignore
  3761/3/Gemfile
  3761/3/Gemfile.lock
  3761/3/Rakefile
  3761/3/app/controllers/application_controller.rb
  3761/3/app/controllers/place_controller.rb
  3761/3/app/controllers/review_controller.rb
  3761/3/app/controllers/user_controller.rb
  3761/3/app/helpers/session_helper.rb
  3761/3/app/helpers/user_helper.rb
  3761/3/app/models/place.rb
  3761/3/app/models/review.rb
  3761/3/app/models/user.rb
  3761/3/app/views/comment_modal_form.erb
  3761/3/app/views/index.erb
  3761/3/app/views/layout.erb
  3761/3/app/views/place.erb
  3761/3/app/views/sign_in.erb
  3761/3/app/views/sign_up.erb
  3761/3/config.ru
  3761/3/config/environment.rb
  3761/3/config/locales/en.yml
  3761/3/db/migrate/20190725084050_create_users_table.rb
  3761/3/db/migrate/20190725084103_create_places_table.rb
  3761/3/db/migrate/20190725084115_create_reviews_table.rb
  3761/3/db/migrate/20190725084243_add_indexes_to_users.rb
  3761/3/db/migrate/20190726125759_add_path_to_image_to_places.rb
  3761/3/db/schema.rb
  3761/3/db/seeds.rb
Labels: requires respond

#480 204/3
  204/3/restoapp.db
  204/3/restoapp/.gitignore
  204/3/restoapp/Gemfile
  204/3/restoapp/Gemfile.lock
  204/3/restoapp/README.md
  204/3/restoapp/Rakefile
  204/3/restoapp/app/controllers/accounts_controller.rb
  204/3/restoapp/app/controllers/application_controller.rb
  204/3/restoapp/app/controllers/restraunts_controller.rb
  204/3/restoapp/app/controllers/reviews_controllers.rb
  204/3/restoapp/app/helpers/review_helper.rb
  204/3/restoapp/app/models/accounts.rb
  204/3/restoapp/app/models/restraunts.rb
  204/3/restoapp/app/models/reviews.rb
  204/3/restoapp/app/services/create_account.rb
  204/3/restoapp/app/services/create_review.rb
  204/3/restoapp/app/services/login.rb
  204/3/restoapp/app/views/account.erb
  204/3/restoapp/app/views/error.erb
  204/3/restoapp/app/views/index.erb
  204/3/restoapp/app/views/layout.erb
  204/3/restoapp/app/views/login.erb
  204/3/restoapp/app/views/login_layout.erb
  204/3/restoapp/app/views/restraunt.erb
  204/3/restoapp/config.ru
  204/3/restoapp/config/environment.rb
  204/3/restoapp/db/migrate/20190725163744_create_accounts_restraunts_reviews_table.rb
  204/3/restoapp/db/schema.rb
  204/3/restoapp/db/seeds.rb
Labels: SPB
