Repository rubizza-camp/summer-2019, pull requests merged in 2019-08, with the labels that each got.

#519 3737 - 3
  3737/3/Gemfile
  3737/3/Gemfile.lock
  3737/3/Rakefile
  3737/3/app/controllers/application_controller.rb
  3737/3/app/controllers/restaraunts_controller.rb
  3737/3/app/controllers/users_controller.rb
  3737/3/app/models/comment.rb
  3737/3/app/models/restaraunt.rb
  3737/3/app/models/user.rb
  3737/3/app/views/index.erb
  3737/3/app/views/layout.erb
  3737/3/app/views/login.erb
  3737/3/app/views/registration.erb
  3737/3/app/views/restaraunt.erb
  3737/3/config.ru
  3737/3/config/environment.rb
  3737/3/db/.gitignore
  3737/3/db/environment.rb
  3737/3/db/migrate/20190724084629_create_user_table.rb
  3737/3/db/migrate/20190724084642_create_comment_table.rb
  3737/3/db/migrate/20190724084655_create_restaraunt_table.rb
  3737/3/db/migrate/20190730110334_add_average_star_to_restaraunts.rb
  3737/3/db/schema.rb
  3737/3/db/seeds.rb
Labels: requires respond

#489 3135 - 3 WIP
  3135/3/.gitignore
  3135/3/Gemfile
  3135/3/Gemfile.lock
  3135/3/Rakefile
  3135/3/app.rb
  3135/3/db/migrate/20190727152144_create_users_table.rb
  3135/3/db/migrate/20190728093635_create_restaurants_table.rb
  3135/3/db/migrate/20190728094703_create_reviews_table.rb
  3135/3/db/schema.rb
  3135/3/db/seeds.rb
  3135/3/models/restaurant.rb
  3135/3/models/review.rb
  3135/3/models/user.rb
  3135/3/views/index.erb
  3135/3/views/layout.erb
  3135/3/views/login_form.erb
  3135/3/views/registration_form.erb
  3135/3/views/restaurant.erb
Labels: SPB, Work in progress

#484 211-3
  211/3/restaurant/Gemfile
  211/3/restaurant/Gemfile.lock
  211/3/restaurant/Rakefile
  211/3/restaurant/app/controllers/application_controller.rb
  211/3/restaurant/app/controllers/base_controller.rb
  211/3/restaurant/app/controllers/restaurants_controller.rb
  211/3/restaurant/app/controllers/reviews_controller.rb
  211/3/restaurant/app/controllers/sessions_controller.rb
  211/3/restaurant/app/decorators/restaurant_decorator.rb
  211/3/restaurant/app/helpers/layout_helper.rb
  211/3/restaurant/app/models/restaurant.rb
  211/3/restaurant/app/models/review.rb
  211/3/restaurant/app/models/user.rb
  211/3/restaurant/app/views/layout.erb
  211/3/restaurant/app/views/restaurants/index.erb
  211/3/restaurant/app/views/restaurants/show.erb
  211/3/restaurant/app/views/sessions/login.erb
  211/3/restaurant/app/views/sessions/signup.erb
  211/3/restaurant/config.ru
  211/3/restaurant/config/environment.rb
  211/3/restaurant/db/migrate/20190725132728_create_restaurants_table.rb
  211/3/restaurant/db/migrate/20190725140543_create_reviews_table.rb
  211/3/restaurant/db/migrate/20190728082529_create_users_table.rb
  211/3/restaurant/db/schema.rb
  211/3/restaurant/db/seeds.rb
Labels: SPB, Work in progress

#530 3570/2
  3570/2/.env.template
  3570/2/.gitignore
  3570/2/Gemfile
  3570/2/Gemfile.lock
  3570/2/bot.rb
  3570/2/commands/checkin.rb
  3570/2/commands/checkout.rb
  3570/2/commands/start.rb
  3570/2/data/numbers.yml
  3570/2/entities/cadet.rb
  3570/2/entities/cadet_registration.rb
  3570/2/helpers/file_helper.rb
Labels: Missed Deadline
